# Generated by Django 4.2.7 on 2025-01-15 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="updated_at",
        ),
    ]
